---
name: Build and deploy Strapi to Azure Web App - strapi-on-azure
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run test --if-present
      - name: Tar files
        run: tar -cf node-app.tar .
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.tar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: Untar files
        run: tar -xf node-app.tar
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: strapi-on-azure-ipractest
          slot-name: Production
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE  }}
          package: .
